{
	"version": 1758546368,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite12-sheet1.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/particles.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/spritefont.png",
		"images/sprite23-sheet0.png",
		"images/sprite23-sheet1.png",
		"images/sprite24-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite29-sheet0.png",
		"media/whack a homer - bgm.m4a",
		"media/whack a homer - bgm.ogg",
		"media/hammer 2.m4a",
		"media/hammer 2.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/hammer 1.m4a",
		"media/hammer 1.ogg",
		"media/audiomass-output.m4a",
		"media/audiomass-output.ogg",
		"media/wrap.m4a",
		"media/wrap.ogg",
		"media/what file bgm.m4a",
		"media/what file bgm.ogg",
		"media/game over wack.m4a",
		"media/game over wack.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}